name: Dependency Vulnerability Check
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight UTC
jobs:
  dependency_vulnerability_check:
    name: Dependency Vulnerability Check
    uses: gold-standard-phantoms/github-actions/.github/workflows/dependency-vulnerability-check.yml@main # Replace 'main' with a tag or commit SHA for production
    with:
      python_version: "3.11" # Replace with the version of Python you want to use
      use_private_pypi: false
      # working_directory: "./backend" # Optional: Working directory for monorepos
      # pip_audit_version: "2.6.1" # Optional: Specific version of pip-audit (defaults to latest)